### ISSUE TITLE
Error running via command line

### ISSUE THREAD

**Issue by stevenmaguire** [wework/we-github-stats#1]
Is this something wrong with my configuration or the gem?

```bash
$ github_stats -o d******d -t 3*****************************************2
WARN: Unresolved specs during Gem::Specification.reset:
      octokit (~> 4.0)
      terminal-table (>= 0)
      faraday (~> 0.8)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
```

Running cleanup does not help the problem?

```bash
$ gem cleanup we-github-stats
Cleaning up installed gems...
Clean Up Complete
```

I've installed, or verified their existence, the underlying gem dependancies and still the problem continues.

For instance: 

```bash
$ gem install octokit
Fetching: octokit-4.6.2.gem (100%)
Successfully installed octokit-4.6.2
Parsing documentation for octokit-4.6.2
Installing ri documentation for octokit-4.6.2
Done installing documentation for octokit after 2 seconds
1 gem installed
```

Halp?

**Comment by philsturgeon** [comment]
Hey Steve! 

![image](https://cloud.githubusercontent.com/assets/67381/21693531/45259d6a-d34f-11e6-9dec-20f45b92e57d.png)

This is for placing issue #1. You're number one. 

This is an odd one, a quick google suggests [it could be an RVM](https://stackoverflow.com/questions/17936340/unresolved-specs-during-gemspecification-reset#18127613) thing. Do you have RVM or rbenv or any similar bundle of joy? 

Try running `bundle exec github_stats ....`

**Comment by stevenmaguire** [comment]
![much excite](https://media.giphy.com/media/7h6qHU0ZLR94Y/source.gif)

I found that SO article as well and couldn't resist adding the first issue here. I am using rbenv, which may be the culprit. I am going to take the bundler approach and add a quick "project" locally that depends on this gem and see how well that helps.

**Comment by stevenmaguire** [comment]
That took care of it. 

Made a `Gemfile`

```ruby
source 'https://rubygems.org'

gem 'we-github-stats'
```

```bash
$ bundle install
--
$ bundle exec github_stats -o d******d -t 3*****************************************2
```
