### ISSUE TITLE
LoadError when running github_stats

### ISSUE THREAD

**Issue by paulmaunders** [wework/we-github-stats#3]
I get the following error when trying to run the script:
```
$ github_stats -o orgname -t 1234567890
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/we-github-stats-0.1.0/bin/github_stats:3:in `<top (required)>'
	from /usr/local/bin/github_stats:22:in `load'
	from /usr/local/bin/github_stats:22:in `<main>'
```

**Comment by philsturgeon** [comment]
Hey there! This is going to be one of those fun ruby bundler errors that we all suffer at some point. 

https://stackoverflow.com/questions/19061774/cannot-load-such-file-bundler-setup-loaderror

You _probably_ want to run `bundle exec github_stats -o orgname -t ...`

**Comment by paulmaunders** [comment]
Actually, it seems just installing bundler did the trick!

`sudo gem install bundler`

Thanks for the tip!
